package com.synctool.service.converter;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.stereotype.Component;

import com.synctool.dto.meta.ColumnMeta;
import com.synctool.dto.meta.ProcedureMeta;
import com.synctool.dto.meta.ViewMeta;
import com.synctool.model.DatabaseType;

/** DB2 (LUW) dialect. */
@Component
public class Db2Dialect extends AbstractSqlDialect {

    @Override
    public DatabaseType.DialectFamily family() {
        return DatabaseType.DialectFamily.DB2;
    }

    @Override
    protected char quoteChar() {
        return '"';
    }

    @Override
    protected String booleanType() {
        // BOOLEAN exists from 11.1 but is not usable as a column type on older releases.
        return "SMALLINT";
    }

    @Override
    protected String tinyIntType() {
        return "SMALLINT";
    }

    @Override
    protected String smallIntType() {
        return "SMALLINT";
    }

    @Override
    protected String intType() {
        return "INTEGER";
    }

    @Override
    protected String bigIntType() {
        return "BIGINT";
    }

    @Override
    protected String floatType() {
        return "REAL";
    }

    @Override
    protected String doubleType() {
        return "DOUBLE";
    }

    @Override
    protected String dateType() {
        return "DATE";
    }

    @Override
    protected String timeType() {
        return "TIME";
    }

    @Override
    protected String timestampType() {
        return "TIMESTAMP";
    }

    @Override
    protected String blobType() {
        return "BLOB(2G)";
    }

    @Override
    protected String clobType() {
        return "CLOB(2G)";
    }

    @Override
    protected String varcharType(int size) {
        // Row-size limits make anything above ~32KB impractical inline.
        if (size <= 0 || size > 32672) {
            return clobType();
        }
        return "VARCHAR(" + size + ")";
    }

    @Override
    protected String binaryType(int size) {
        if (size <= 0 || size > 32672) {
            return blobType();
        }
        return "VARBINARY(" + size + ")";
    }

    @Override
    protected int maxIdentifierLength() {
        return 128;
    }

    @Override
    protected boolean indexNamesAreGlobal() {
        return true;
    }

    @Override
    protected String autoIncrementClause() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String getModifyColumnSql(String schema, String table, ColumnMeta column,
                                     DatabaseType sourceType) {
        return "ALTER TABLE " + qualify(schema, table) + " ALTER COLUMN "
                + quoteIdentifier(column.getName()) + " SET DATA TYPE "
                + mapType(column, sourceType);
    }

    @Override
    public String getAddColumnSql(String schema, String table, ColumnMeta column,
                                  DatabaseType sourceType) {
        return "ALTER TABLE " + qualify(schema, table) + " ADD COLUMN "
                + columnDefinition(column, sourceType);
    }

    @Override
    public List<String> getCreateViewSql(ViewMeta view, String schema, DatabaseType sourceType) {
        List<String> stmts = new ArrayList<>();
        // DB2 has no CREATE OR REPLACE VIEW before 9.7 and no IF EXISTS on DROP; the
        // engine tolerates the drop failing, which the executor treats as non-fatal.
        stmts.add("DROP VIEW " + qualify(schema, view.getName()));
        String def = view.getDefinition();
        if (def != null && def.trim().toUpperCase().startsWith("CREATE")) {
            stmts.add(def.trim());
        } else {
            stmts.add("CREATE VIEW " + qualify(schema, view.getName()) + " AS " + def);
        }
        return stmts;
    }

    @Override
    public List<String> getCreateProcedureSql(ProcedureMeta procedure, String schema,
                                              DatabaseType sourceType) {
        String body = procedure.getDefinition();
        if (body == null || body.isBlank()) {
            return List.of();
        }
        List<String> stmts = new ArrayList<>();
        stmts.add("DROP " + (procedure.isFunction() ? "FUNCTION " : "PROCEDURE ")
                + qualify(schema, procedure.getName()));
        String trimmed = body.trim();
        if (trimmed.toUpperCase().startsWith("CREATE")) {
            stmts.add(trimmed);
        } else {
            String params = procedure.getParameters().stream()
                    .filter(p -> !"RETURN".equalsIgnoreCase(p.getMode()))
                    .map(p -> p.getMode() + " " + quoteIdentifier(p.getName()) + " " + p.getTypeName())
                    .collect(Collectors.joining(", "));
            stmts.add("CREATE " + (procedure.isFunction() ? "FUNCTION " : "PROCEDURE ")
                    + qualify(schema, procedure.getName()) + " (" + params + ")\n"
                    + "LANGUAGE SQL\n" + trimmed);
        }
        return stmts;
    }

    /** DB2 MERGE, with the row source built from a VALUES list over SYSIBM.SYSDUMMY1. */
    @Override
    public String getUpsertSql(String schema, String table, List<String> columns,
                               List<String> pkColumns) {
        if (pkColumns == null || pkColumns.isEmpty()) {
            return "INSERT INTO " + qualify(schema, table) + " (" + quotedList(columns)
                    + ") VALUES (" + placeholders(columns.size()) + ")";
        }
        String onClause = pkColumns.stream()
                .map(c -> "t." + quoteIdentifier(c) + " = s." + quoteIdentifier(c))
                .collect(Collectors.joining(" AND "));
        List<String> updatable = nonKeyColumns(columns, pkColumns);

        StringBuilder sb = new StringBuilder();
        sb.append("MERGE INTO ").append(qualify(schema, table)).append(" AS t USING (VALUES (")
                .append(placeholders(columns.size())).append(")) AS s (")
                .append(quotedList(columns)).append(") ON ").append(onClause);
        if (!updatable.isEmpty()) {
            String updates = updatable.stream()
                    .map(c -> "t." + quoteIdentifier(c) + " = s." + quoteIdentifier(c))
                    .collect(Collectors.joining(", "));
            sb.append(" WHEN MATCHED THEN UPDATE SET ").append(updates);
        }
        String insertVals = columns.stream()
                .map(c -> "s." + quoteIdentifier(c))
                .collect(Collectors.joining(", "));
        sb.append(" WHEN NOT MATCHED THEN INSERT (").append(quotedList(columns))
                .append(") VALUES (").append(insertVals).append(')');
        return sb.toString();
    }

    @Override
    public String getPaginationSql(String baseSql, long offset, int limit) {
        return baseSql + " LIMIT " + limit + " OFFSET " + offset;
    }

    @Override
    public String getTruncateSql(String schema, String table) {
        // DB2 requires IMMEDIATE for the statement to take effect without a commit.
        return "TRUNCATE TABLE " + qualify(schema, table) + " IMMEDIATE";
    }
}
