package com.synctool.service.converter;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.stereotype.Component;

import com.synctool.dto.meta.ColumnMeta;
import com.synctool.dto.meta.ProcedureMeta;
import com.synctool.dto.meta.ViewMeta;
import com.synctool.model.DatabaseType;

/** Oracle and 达梦 (DM) dialect. */
@Component
public class OracleDialect extends AbstractSqlDialect {

    @Override
    public DatabaseType.DialectFamily family() {
        return DatabaseType.DialectFamily.ORACLE;
    }

    @Override
    protected char quoteChar() {
        return '"';
    }

    @Override
    protected String booleanType() {
        // Oracle had no BOOLEAN column type before 23c.
        return "NUMBER(1)";
    }

    @Override
    protected String tinyIntType() {
        return "NUMBER(3)";
    }

    @Override
    protected String smallIntType() {
        return "NUMBER(5)";
    }

    @Override
    protected String intType() {
        return "NUMBER(10)";
    }

    @Override
    protected String bigIntType() {
        return "NUMBER(19)";
    }

    @Override
    protected String floatType() {
        return "BINARY_FLOAT";
    }

    @Override
    protected String doubleType() {
        return "BINARY_DOUBLE";
    }

    @Override
    protected String dateType() {
        return "DATE";
    }

    @Override
    protected String timeType() {
        // Oracle has no TIME type; INTERVAL is the closest portable equivalent, but a
        // timestamp keeps the value readable and comparable.
        return "TIMESTAMP";
    }

    @Override
    protected String timestampType() {
        return "TIMESTAMP";
    }

    @Override
    protected String timestampTzType() {
        return "TIMESTAMP WITH TIME ZONE";
    }

    @Override
    protected String blobType() {
        return "BLOB";
    }

    @Override
    protected String clobType() {
        return "CLOB";
    }

    @Override
    protected String charType(int size) {
        return "CHAR(" + Math.min(size, 2000) + ")";
    }

    @Override
    protected String varcharType(int size) {
        // VARCHAR2 caps at 4000 bytes unless extended types are enabled.
        if (size <= 0 || size > 4000) {
            return clobType();
        }
        return "VARCHAR2(" + size + ")";
    }

    @Override
    protected String binaryType(int size) {
        if (size <= 0 || size > 2000) {
            return blobType();
        }
        return "RAW(" + size + ")";
    }

    @Override
    protected int maxIdentifierLength() {
        // 30 before 12.2; 128 after. 30 is the safe choice across versions.
        return 30;
    }

    @Override
    protected boolean indexNamesAreGlobal() {
        return true;
    }

    @Override
    protected String currentTimestampFunction() {
        return "SYSTIMESTAMP";
    }

    /**
     * Oracle 12c+ identity column. On older releases this fails and the user must create a
     * sequence and trigger; the failure is logged against the specific table.
     */
    @Override
    protected String autoIncrementColumnType(ColumnMeta col, DatabaseType sourceType) {
        return mapType(col, sourceType) + " GENERATED BY DEFAULT ON NULL AS IDENTITY";
    }

    @Override
    public String getModifyColumnSql(String schema, String table, ColumnMeta column,
                                     DatabaseType sourceType) {
        StringBuilder sb = new StringBuilder("ALTER TABLE ")
                .append(qualify(schema, table))
                .append(" MODIFY (")
                .append(quoteIdentifier(column.getName())).append(' ')
                .append(mapType(column, sourceType));
        // Oracle rejects MODIFY with NOT NULL when the column is already NOT NULL, so only
        // state nullability when it is being relaxed to NULL.
        if (column.isNullable()) {
            sb.append(" NULL");
        } else {
            sb.append(" NOT NULL");
        }
        return sb.append(')').toString();
    }

    @Override
    public String getAddColumnSql(String schema, String table, ColumnMeta column,
                                  DatabaseType sourceType) {
        // Oracle's ADD takes no COLUMN keyword.
        return "ALTER TABLE " + qualify(schema, table) + " ADD ("
                + columnDefinition(column, sourceType) + ")";
    }

    @Override
    public String getDropColumnSql(String schema, String table, String columnName) {
        return "ALTER TABLE " + qualify(schema, table) + " DROP COLUMN " + quoteIdentifier(columnName);
    }

    @Override
    public List<String> getCreateViewSql(ViewMeta view, String schema, DatabaseType sourceType) {
        return List.of("CREATE OR REPLACE VIEW " + qualify(schema, view.getName())
                + " AS " + stripTrailingSemicolon(view.getDefinition()));
    }

    @Override
    public List<String> getCreateProcedureSql(ProcedureMeta procedure, String schema,
                                              DatabaseType sourceType) {
        String body = procedure.getDefinition();
        if (body == null || body.isBlank()) {
            return List.of();
        }
        String trimmed = stripTrailingSlash(body.trim());
        List<String> stmts = new ArrayList<>();
        String upper = trimmed.toUpperCase();
        if (upper.startsWith("CREATE OR REPLACE")) {
            stmts.add(trimmed);
        } else if (upper.startsWith("CREATE")) {
            // Make it re-runnable: ALL_SOURCE stores "PROCEDURE x" without CREATE.
            stmts.add(trimmed.replaceFirst("(?i)^CREATE\\s+", "CREATE OR REPLACE "));
        } else if (upper.startsWith("PROCEDURE") || upper.startsWith("FUNCTION")) {
            stmts.add("CREATE OR REPLACE " + trimmed);
        } else {
            stmts.add("CREATE OR REPLACE " + (procedure.isFunction() ? "FUNCTION " : "PROCEDURE ")
                    + qualify(schema, procedure.getName()) + " AS\n" + trimmed);
        }
        return stmts;
    }

    private String stripTrailingSemicolon(String sql) {
        if (sql == null) {
            return null;
        }
        String s = sql.trim();
        // Oracle rejects a trailing semicolon on a plain DDL statement submitted via JDBC.
        return s.endsWith(";") ? s.substring(0, s.length() - 1) : s;
    }

    /** Removes the SQL*Plus terminator, which JDBC does not accept. */
    private String stripTrailingSlash(String sql) {
        String s = sql.trim();
        while (s.endsWith("/")) {
            s = s.substring(0, s.length() - 1).trim();
        }
        return s;
    }

    /**
     * {@code MERGE} is Oracle's idempotent upsert. Values are bound twice — once for the
     * USING row source and once for the INSERT list — which is what
     * {@link #upsertBindOrder} encodes.
     */
    @Override
    public String getUpsertSql(String schema, String table, List<String> columns,
                               List<String> pkColumns) {
        if (pkColumns == null || pkColumns.isEmpty()) {
            return "INSERT INTO " + qualify(schema, table) + " (" + quotedList(columns)
                    + ") VALUES (" + placeholders(columns.size()) + ")";
        }
        String using = columns.stream()
                .map(c -> "? AS " + quoteIdentifier(c))
                .collect(Collectors.joining(", "));
        String onClause = pkColumns.stream()
                .map(c -> "t." + quoteIdentifier(c) + " = s." + quoteIdentifier(c))
                .collect(Collectors.joining(" AND "));
        List<String> updatable = nonKeyColumns(columns, pkColumns);

        StringBuilder sb = new StringBuilder();
        sb.append("MERGE INTO ").append(qualify(schema, table)).append(" t USING (SELECT ")
                .append(using).append(" FROM DUAL) s ON (").append(onClause).append(')');
        if (!updatable.isEmpty()) {
            String updates = updatable.stream()
                    .map(c -> "t." + quoteIdentifier(c) + " = s." + quoteIdentifier(c))
                    .collect(Collectors.joining(", "));
            sb.append(" WHEN MATCHED THEN UPDATE SET ").append(updates);
        }
        String insertCols = quotedList(columns);
        String insertVals = columns.stream()
                .map(c -> "s." + quoteIdentifier(c))
                .collect(Collectors.joining(", "));
        sb.append(" WHEN NOT MATCHED THEN INSERT (").append(insertCols)
                .append(") VALUES (").append(insertVals).append(')');
        return sb.toString();
    }

    @Override
    public List<String> upsertBindOrder(List<String> columns, List<String> pkColumns) {
        // The MERGE names each value once, in the USING clause.
        return new ArrayList<>(columns);
    }

    @Override
    public String getPaginationSql(String baseSql, long offset, int limit) {
        // OFFSET/FETCH requires 12c; ROWNUM nesting works on every supported release.
        return "SELECT * FROM (SELECT a.*, ROWNUM rnum_ FROM (" + baseSql + ") a "
                + "WHERE ROWNUM <= " + (offset + limit) + ") WHERE rnum_ > " + offset;
    }

    @Override
    public String getTruncateSql(String schema, String table) {
        return "TRUNCATE TABLE " + qualify(schema, table);
    }
}
